import { withApollo } from '@/lib/apollo/withApollo';
import { GetStaticProps } from 'next';
import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};
export const getStaticProps: GetStaticProps = async () => {
  return { props: {} };
};

export default withApollo(Home);
